title: Irem Gurek
description: [Welcome to my portfolio! I'm passionate about Data Science, and my portfolio showcases my diverse range of SQL, Python, Data Analysis]
logo: Irem_Portfolio/iremg.png
theme: jekyll-theme-minimal
